export const API_KEY = 'api_key=eKe4TcSvYOBAjxJYbt0cc2UESWgsz8Yq'
export const SEARCH_REQUEST_URL = 'https://api.giphy.com/v1/gifs/search?'
export const TRENDING_REQUEST_URL = 'https://api.giphy.com/v1/gifs/trending?'
export const RANDOM_REQUEST_URL = 'https://api.giphy.com/v1/gifs/random?'
export const LIMIT = '&limit=15'
export const RATING = '&rating=g'